FROM python:3.9

RUN apt-get -y update
RUN apt-get -y upgrade

RUN pip3 install --upgrade pip
RUN pip3 install --upgrade setuptools
RUN pip3 install --upgrade wheel
RUN pip3 install --upgrade 'numpy>=1.17.5,<=1.18.3'

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

RUN apt-get install cloc golang-go pkg-config libglib2.0-dev libjson-c-dev libpq-dev -y
RUN go get -u github.com/boyter/scc/

RUN git clone https://github.com/fossology/fossology
RUN (cd fossology/src/nomos/agent && make -f Makefile.sa FO_LDFLAGS="-lglib-2.0 -lpq  -lglib-2.0 -ljson-c -lpthread -lrt")
